package com.in.cafe.domain;

import javax.persistence.*;

import java.util.Arrays;
import java.util.Objects;

import static javax.persistence.GenerationType.IDENTITY;


/**
 * TblTblClient generated by hbm2java
 */
@Entity
@Table(name = "tbl_client")
public class TblClient extends AbstractAuditingEntity implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Long clientId;
	private String domainName;
	private String address;
	private int countryId;
	private int stateId;
	private String cityName;
	private long timezoneId;
	private String clientCategory;
	private int decimalValueUpto;
	private byte[] logo;
	private String domainHost;
	private String clientName;
	private String fileName;
	private  Integer isWorkflowReq;

	private int amtDspIn;


    @Column(name = "amt_dsp_in")
    public int getAmtDspIn() {
        return amtDspIn;
    }

    public void setAmtDspIn(int amtDspIn) {
        this.amtDspIn = amtDspIn;
    }

    @Column(name = "is_workflow_req")
    public Integer getIsWorkflowReq() {
        return isWorkflowReq;
    }

    public void setIsWorkflowReq(Integer isWorkflowReq) {
        this.isWorkflowReq = isWorkflowReq;
    }

    @Column(name = "file_name", length = 500)
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * @return the domainHost
	 */

	@Column(name = "domain_host", nullable = false, length = 500)
	public String getDomainHost() {
		return domainHost;
	}

	/**
	 * @param domainHost the domainHost to set
	 */
	public void setDomainHost(String domainHost) {
		this.domainHost = domainHost;
	}


	@Column(name = "client_name", nullable = false, length = 500)
	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	/**
	 * @return the clientCategory
	 */

	@Column(name = "client_category", length = 500)
	public String getClientCategory() {
		return clientCategory;
	}

	/**
	 * @param clientCategory the clientCategory to set
	 */
	public void setClientCategory(String clientCategory) {
		this.clientCategory = clientCategory;
	}

	public TblClient() {
		super();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "client_id", unique = true, nullable = false)
	public Long getClientId() {
		return this.clientId;
	}

	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	@Column(name = "domain_name", nullable = false, length = 500)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "address", nullable = false, length = 5000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "country_id", nullable = false)
	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	@Column(name = "state_id", nullable = false)
	public int getStateId() {
		return this.stateId;
	}

	public void setStateId(int stateId) {
		this.stateId = stateId;
	}

    @Column(name = "city_name", nullable = false)
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }



	@Column(name = "timezone_id", nullable = false)
	public long getTimezoneId() {
		return this.timezoneId;
	}

	public void setTimezoneId(long timezoneId) {
		this.timezoneId = timezoneId;
	}

	@Column(name = "decimal_value_upto", nullable = false)
	public int getDecimalValueUpto() {
		return this.decimalValueUpto;
	}

	public void setDecimalValueUpto(int decimalValueUpto) {
		this.decimalValueUpto = decimalValueUpto;
	}
	@Lob
	@Column(name = "logo")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	/**
	 * @param clientId
	 */
	public TblClient(Long clientId) {
		super();
		this.clientId = clientId;
	}


    public String getCityName() {
        return cityName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        TblClient tblClient = (TblClient) o;
        return countryId == tblClient.countryId &&
            stateId == tblClient.stateId &&
            timezoneId == tblClient.timezoneId &&
            decimalValueUpto == tblClient.decimalValueUpto &&
            Objects.equals(clientId, tblClient.clientId) &&
            Objects.equals(domainName, tblClient.domainName) &&
            Objects.equals(address, tblClient.address) &&
            Objects.equals(cityName, tblClient.cityName) &&
            Objects.equals(clientCategory, tblClient.clientCategory) &&
            Arrays.equals(logo, tblClient.logo) &&
            Objects.equals(domainHost, tblClient.domainHost) &&
            Objects.equals(clientName, tblClient.clientName) &&
            Objects.equals(fileName, tblClient.fileName) &&
            Objects.equals(isWorkflowReq, tblClient.isWorkflowReq);
    }

    @Override
    public int hashCode() {
        int result = Objects.hash(super.hashCode(), clientId, domainName, address, countryId, stateId, cityName, timezoneId, clientCategory, decimalValueUpto, domainHost, clientName, fileName, isWorkflowReq);
        result = 31 * result + Arrays.hashCode(logo);
        return result;
    }
}
